version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    # for live reload in dev, comment out in prod
    volumes:
      - ./frontend:/app